apiVersion: v1
kind: Service
metadata:
  name: market-data-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: market-data-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
