"""initial

Revision ID: 1a32a88f63e5
Revises:
Create Date: 2024-01-28 19:49:36.564309

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a32a88f63e5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dam_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "settlement_period_start_datetime",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("a1_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("a2_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("e1_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("e2_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("n1_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("n2_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("n3_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("s1_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("s2_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("s3_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("w1_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("w2_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("w3_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("mcp_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rtm_prices",
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "settlement_period_start_datetime",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("a1_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("a2_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("e1_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("e2_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("n1_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("n2_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("n3_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("s1_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("s2_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("s3_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("w1_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("w2_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("w3_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.Column("mcp_price_in_rs_per_mwh", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rtm_prices")
    op.drop_table("dam_prices")
    # ### end Alembic commands ###
