"""settlement datetime uniqueness

Revision ID: b1dfc5daec52
Revises: 1a32a88f63e5
Create Date: 2024-01-29 01:34:01.029425

"""
from typing import Sequence, Union

import sqlalchemy as sa  # noqa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1dfc5daec52"
down_revision: Union[str, None] = "1a32a88f63e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "dam_prices", ["settlement_period_start_datetime"]
    )
    op.create_unique_constraint(
        None, "rtm_prices", ["settlement_period_start_datetime"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rtm_prices", type_="unique")
    op.drop_constraint(None, "dam_prices", type_="unique")
    # ### end Alembic commands ###
